spring.application.name=proyecto-clinica

server.port=${PORT:8080}

spring.datasource.url=mysql://root:fDUatWbkPSMsqpoIsavLChMjuWLtSgoy@shortline.proxy.rlwy.net:26289/railway
spring.datasource.username= root
spring.datasource.password=fDUatWbkPSMsqpoIsavLChMjuWLtSgoy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
